"""Adding User model

Revision ID: 4a89b1da5a1f
Revises: 70e7e149c998
Create Date: 2023-04-11 19:57:11.801709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a89b1da5a1f'
down_revision = '70e7e149c998'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
