"""Upgrade config

Revision ID: 6102ec2a48b9
Revises: 9895d93f657e
Create Date: 2023-03-28 20:00:38.451249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6102ec2a48b9'
down_revision = '9895d93f657e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picture_id'), 'picture', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picture_id'), table_name='picture')
    op.drop_table('picture')
    # ### end Alembic commands ###
