"""Update field username

Revision ID: 70e7e149c998
Revises: c0245f188e37
Create Date: 2023-03-29 13:43:05.670715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e7e149c998'
down_revision = 'c0245f188e37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
