"""Update field username

Revision ID: 8510e2723638
Revises: ae62cbc0f5c8
Create Date: 2023-03-29 00:55:38.977381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8510e2723638'
down_revision = 'ae62cbc0f5c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
