"""Update field picture_id

Revision ID: ae62cbc0f5c8
Revises: 26e63cc8693a
Create Date: 2023-03-28 21:23:56.655114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae62cbc0f5c8'
down_revision = '26e63cc8693a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
