"""Update field size

Revision ID: b7f73f840f6f
Revises: 8510e2723638
Create Date: 2023-03-29 11:23:54.191417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f73f840f6f'
down_revision = '8510e2723638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
