"""Update field size

Revision ID: c0245f188e37
Revises: b7f73f840f6f
Create Date: 2023-03-29 11:45:30.912193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0245f188e37'
down_revision = 'b7f73f840f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'user')
    # ### end Alembic commands ###
